# Generated by Django 3.1.7 on 2022-04-01 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anDebut', models.IntegerField()),
                ('anFin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('niveau', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeEc', models.CharField(max_length=60)),
                ('nomEc', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectif', models.TextField(blank=True, null=True)),
                ('competences', models.TextField(blank=True, null=True)),
                ('prerequis', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('coefficient', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=60)),
                ('numTel', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('dateEntree', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'entrée de l'étudiant")),
                ('dateSortie', models.DateField(null=True)),
                ('anneeScolaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.anneescolaire')),
                ('ec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.ec')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('codePermanent', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=60)),
                ('prenom', models.CharField(blank=True, max_length=60)),
                ('adresse', models.CharField(blank=True, max_length=60)),
                ('numTel', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=60, unique=True)),
                ('dateNaiss', models.DateField(blank=True)),
                ('lieuNaiss', models.CharField(blank=True, max_length=60)),
                ('dateEntree', models.DateField(default=django.utils.timezone.now, null=True, verbose_name="Date d'entrée de l'étudiant")),
                ('dateSortie', models.DateField(blank=True, null=True)),
                ('delegue', models.BooleanField(blank=True, default=False)),
                ('password', models.CharField(blank=True, max_length=60)),
                ('sexe', models.CharField(blank=True, max_length=60)),
                ('nationalite', models.CharField(blank=True, max_length=60)),
                ('nomIdentifiant', models.CharField(max_length=10)),
                ('numIdentifiant', models.IntegerField(blank=True)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='FilereCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFiliere', models.CharField(max_length=60, unique=True)),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.anneescolaire')),
                ('cycle', models.ManyToManyField(to='UniteEnseignement.Cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Modalite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraisInscription', models.IntegerField()),
                ('mensualite', models.IntegerField()),
                ('anneeScolaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSemestre', models.IntegerField()),
                ('filereCycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.filerecycle')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeUE', models.CharField(max_length=60, unique=True)),
                ('nomUE', models.CharField(max_length=60, unique=True)),
                ('credit', models.IntegerField()),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.anneescolaire')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm', models.IntegerField(unique=True)),
                ('tp', models.IntegerField(unique=True)),
                ('tpe', models.IntegerField(unique=True)),
                ('td', models.IntegerField(unique=True)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.ec')),
            ],
        ),
        migrations.CreateModel(
            name='RespoScolarite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=60)),
                ('numTel', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('anneeScolaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='RespoFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=60)),
                ('numTel', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('dateEntree', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'entrée de l'étudiant")),
                ('dateSortie', models.DateField(null=True)),
                ('role', models.CharField(max_length=60)),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.anneescolaire')),
                ('ec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.ec')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(blank=True, max_length=60)),
                ('prenom', models.CharField(blank=True, max_length=60)),
                ('adresse', models.CharField(blank=True, max_length=60)),
                ('numTel', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=60, unique=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='ModFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.filiere')),
                ('modalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.modalite')),
            ],
        ),
        migrations.AddField(
            model_name='modalite',
            name='filiere',
            field=models.ManyToManyField(through='UniteEnseignement.ModFiliere', to='UniteEnseignement.Filiere'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeScolaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.anneescolaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.etudiant')),
                ('filiereCycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.filerecycle')),
                ('respoScolarite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.resposcolarite')),
            ],
        ),
        migrations.AddField(
            model_name='filerecycle',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.filiere'),
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('numTel', models.IntegerField()),
                ('siteWeb', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('anneeScolaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='EnsFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RespoFiliere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.filiere')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='filiere',
            field=models.ManyToManyField(through='UniteEnseignement.EnsFiliere', to='UniteEnseignement.Filiere'),
        ),
        migrations.AddField(
            model_name='ec',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniteEnseignement.ue'),
        ),
    ]
