# Generated by Django 4.0.5 on 2022-06-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_student_teacher_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facutly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('appreciation', models.TextField()),
                ('semester', models.CharField(choices=[('first_semester', 'Semestre 1'), ('second_semester', 'Semestre 2')], default='', max_length=70)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
