# Generated by Django 4.0.5 on 2022-06-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacher_faculty_teacher_user_student_faculty_and_more'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facutly',
            new_name='Faculty',
        ),
    ]
