# Generated by Django 4.0.5 on 2022-06-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_rename_facutly_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credit', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('semester', models.CharField(choices=[('first_semester', 'Semestre 1'), ('second_semester', 'Semestre 2')], default='', max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.AddField(
            model_name='grade',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='unit.lecture'),
        ),
    ]
