# Generated by Django 4.0.5 on 2022-06-26 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_teacher_conduct_student_conduct'),
        ('unit', '0004_faculty_created_at_faculty_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.teacher'),
        ),
    ]
