# Generated by Django 4.0.5 on 2022-07-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('mic', 'Multimedia'), ('tr', 'Telecom. & Reseaux')], default='mic', max_length=10),
        ),
    ]
