# Generated by Django 4.0.5 on 2022-07-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_student_faculty_student_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('available', models.BooleanField(default=True)),
                ('sexe', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], default='', max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('ended_at', models.DateTimeField()),
                ('photo', models.ImageField(default='staff.png', upload_to='images/staff/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
