# Generated by Django 4.0.5 on 2022-06-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacher_faculty_teacher_user_student_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='conduct',
            field=models.CharField(choices=[('good', 'Bonne'), ('bad', 'Mauvaise'), ('yellow_flag', 'Rectifiable'), ('red_flag', 'Insupportable')], default='', max_length=20),
        ),
    ]
