# Generated by Django 4.0.5 on 2022-07-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_student_program_student_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='faculty',
        ),
    ]
