# Generated by Django 4.0.5 on 2022-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_teacher_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('mic', 'Multimedia'), ('tr', 'Telecom. & Reseaux')], default='', max_length=100),
        ),
    ]
