# Generated by Django 4.0.5 on 2022-06-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teacher_conduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='count_available',
            field=models.IntegerField(default=0),
        ),
    ]
