# Generated by Django 4.0.5 on 2022-07-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_student_faculty_student_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='conduct',
        ),
    ]
