# Generated by Django 4.0.5 on 2022-06-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_lecture_remove_grade_credit_remove_grade_semester_and_more'),
        ('accounts', '0007_teacher_available_teacher_count_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_facutly', to='unit.faculty'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tc_faculty', to='unit.faculty'),
        ),
    ]
