# Generated by Django 4.0.5 on 2022-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_faculty_alter_teacher_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='teacher.png', upload_to='images/teachers/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='student.png', upload_to='images/students/'),
        ),
    ]
