# Generated by Django 4.0.5 on 2022-06-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teacher_photo_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='conduct',
        ),
        migrations.AddField(
            model_name='student',
            name='conduct',
            field=models.CharField(choices=[('good', 'Bonne'), ('bad', 'Mauvaise'), ('yellow_flag', 'Rectifiable'), ('red_flag', 'Insupportable')], default='', max_length=20),
        ),
    ]
