# Generated by Django 4.0.5 on 2022-06-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_teacher_conduct_student_conduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sexe',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('full_time', 'Permanent'), ('part_time', 'Non Permanent')], default='', max_length=100),
        ),
    ]
