# Generated by Django 4.0.5 on 2022-06-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_teacher_nationality_teacher_sexe_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='count_available',
        ),
    ]
