# Generated by Django 4.0.5 on 2022-06-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_student_teacher_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('full_year_payment', 'Paiement annuel'), ('half_year_payment', 'Paiement semestriel')], default='half_year_payment', max_length=100)),
                ('amount', models.BigIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.student')),
            ],
        ),
    ]
